### PR TITLE
Auto Suggest route based on title field input

### PR DESCRIPTION
**Pull request by VSEphpbb**
This is a little GUI enhancement that will auto-fill the route field after the title field is filled in, with a suggestion for the route based on the title field. It pulls out any invalid chars so it will be valid. The main reason for this is because so many people have seemed to not understand what to put in the route field, my hope is this will give them a lightbulb moment, whether they choose to use the auto-filled suggestion or then replace it with their own.

### CODE REVIEW

**Comment by VSEphpbb** [comment]
@rxu @michaelcullum

**Comment by rxu** [comment]
Autosuggestion applies only if the route filed is empty. F.e. if you enter the page title you get the route suggested, but if you have edited the title, suggested route don't get changed. This could be addressed probably.

**Comment by VSEphpbb** [comment]
You don't want to change the route if it already has a value. That would bother people, because it could be changing what they wanted it to be.

**Comment by rxu** [comment]
Ok, but this is probably still the case when the route config entry is empty in the db (that is, you're setting it for the 1st time).

**Comment by VSEphpbb** [comment]
Not really. Imagine a user enters a title, and a route suggestion is made. They change the route to something else though. Then they decide to change. We don't want to auto-edit their route field at that point.

**Comment by VSEphpbb** [comment]
It's just supposed to be a suggestion. We're not really trying to fill the field for them, just give them an idea of what the route field is supposed to contain.

**Comment by rxu** [comment]
Agreed.
One more thing is the chars replacement. Every ```[^a-z0-9-_\s]``` char is got replaced by a dash, so you can get several dashes in some cases, like ```my-test---page``` in suggested route.
Probably could be replaced with only 1.

**Comment by VSEphpbb** [comment]
Actually, it's only whitespaces that get replaced with a dash. So if you've got multiple dashes, you've got multiple spaces in the title.

**Comment by rxu** [comment]
Other than that, the PR looks ok :wink:

**Comment by VSEphpbb** [comment]
Updated for whitespace shenanigans

**Pull request merged**
